### ISSUE TITLE
Null character not supported

### ISSUE THREAD

**Issue by dgouldin** [jdunck/python-unicodecsv#32]
>>> import unicodecsv
    >>> from cStringIO import StringIO
    >>> f = StringIO('"\0"')
    >>> f.seek(0)
    >>> r = unicodecsv.reader(f, encoding='utf-8')
    >>> row = r.next()
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/app/.heroku/python/lib/python2.7/site-packages/unicodecsv/__init__.py", line 106, in next
        row = self.reader.next()
    Error: line contains NULL byte

**Comment by jdunck** [comment]
Closing since no response in a while, though reopen if you have suggestions for addressing w/o monkey-patching stdlib.
