### ISSUE TITLE
unicodecsv.DictReader still throws "UnicodeEncodeError: 'ascii' " with unicode StringIO

### ISSUE THREAD

**Issue by themantalope** [jdunck/python-unicodecsv#61]
Here's some sample code, and the error that I'm getting

```python
import unicodecsv as csv
import codecs

handle = codecs.open('a_utf8_encoded_file.txt','r','utf-8')

data = handle.read()

handle.close()

f = StringIO(data)

reader = csv.DictReader(f, delimiter=',')

for line in reader:
  print line
```

And the error I get: 

```python
Traceback (most recent call last):
  File "create_and_refresh_test_copy.py", line 125, in <module>
    createTests(gauth,formFileName,localTestName,localKeyName,remoteTestName,remoteKeyName)
  File "create_and_refresh_test_copy.py", line 60, in createTests
    tc = TestCreator(temp_csv_name)
  File "/home/matt/class_practice_tests/testcreator.py", line 27, in __init__
    self._parseFileString(csvFile)
  File "/home/matt/class_practice_tests/testcreator.py", line 56, in _parseFileString
    for line in reader:
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 218, in next
    row = csv.DictReader.next(self)
  File "/usr/lib/python2.7/csv.py", line 108, in next
    row = self.reader.next()
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 118, in next
    row = self.reader.next()
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 244: ordinal not in range(128)
```

**Comment by themantalope** [comment]
It seems that the csv.DictReader is trying to get the next line, not the unicodecsv.DictReader object

**Comment by vdboor** [comment]
I'm getting this same error,

In `unicodecsv/py2.py`, the `unicodecsv.DictReader` first asks the orginal csv file to read the line:

```
    def next(self):
        row = csv.DictReader.next(self)
```

**Comment by vdboor** [comment]
Solved it myself!

It turns out the original file should be opened without a codec, so just using `open()` or `codecs.open(filename, 'rb')` without giving an encoding. The encoding conversion happens in `unicodecsv`.

**Comment by themantalope** [comment]
Hi Guys,

 Yep, same thing. Found out that opening a regularly encoded python str
stream (with StringIO) did the trick.

-Matt

**Comment by jdunck** [comment]
In 7241622d748, I've added a note about this stumbling block.  Closing here.

**Comment by PJAMESR** [comment]
I am still receiving a similar problem,
```
Traceback (most recent call last):
  File "C:\Users\pjame\Desktop\DeepMoji-master\examples\score_texts_emojis.py", line 25, in <module>
    for row in reader:
  File "C:\Python27\lib\site-packages\unicodecsv\py2.py", line 217, in next
    row = csv.DictReader.next(self)
  File "C:\Python27\lib\csv.py", line 108, in next
    row = self.reader.next()
  File "C:\Python27\lib\site-packages\unicodecsv\py2.py", line 128, in next
    for value in row]
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 254: unexpected end of data
```
