### ISSUE TITLE
working with streams

### ISSUE THREAD

**Issue by willembressers** [jdunck/python-unicodecsv#73]
I'm writing an mapReduce script (and thus are working with input / output streams).

If i use the `unicodecsv` module
```
#!/usr/bin/python
import sys
import unicodecsv as csv


def mapper():
    reader = csv.reader(sys.stdin, delimiter='\t')
    # writer = csv.writer(sys.stdout, delimiter='\t', quotechar='"', quoting=csv.QUOTE_ALL)

    for line in reader:
        print line
```

Then i get the error:
```
Traceback (most recent call last):
  File "scripts/streaming/adwords/mapper.py", line 30, in <module>
    mapper()
  File "scripts/streaming/adwords/mapper.py", line 10, in mapper
    for line in reader:
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 117, in next
    row = self.reader.next()
_csv.Error: line contains NULL byte
```

I don't know how to resolve this issue. I tried almost everything,  even opening and saving (in utf-8) the with libreoffice, but that can't be a solution because my csv files are to big for libreOffice.

Preferably i want to read the (unicode (i guess)) input stream, map it line by line (and encode it to utf-8) and write it like `writer.writerow((line[0] + line[2], line[5]))` so that my reducer.py doesn't have to hassle with encodings.

any help would deeply be appreciated.

**Comment by ryanhiebert** [comment]
The first issue is that you're not using the right encoding. The `unicodecsv` reader requires a binary-opened file. the `reader` function takes an `encoding` argument, which defaults to `utf-8`, which is incorrect for you.

Unfortunately, `unicodecsv` doesn't yet support `utf-16`, because the underlying reader doesn't allow for any null bytes. We have talked about a couple ideas for fixing it, but it hasn't been implemented yet.
