### ISSUE TITLE
ttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by jianboy** [jdunck/python-unicodecsv#79]

**Comment by PoisonousJohn** [comment]
Platform: Windows
Python: 3.6.3
stacktrace:
```
Traceback (most recent call last):
  File ".\csv_to_json.py", line 43, in <module>
    main(sys.argv[1:])
  File ".\csv_to_json.py", line 32, in main
    print(json.dumps([row for row in rows]))
  File ".\csv_to_json.py", line 32, in <listcomp>
    print(json.dumps([row for row in rows]))
  File "C:\Users\ivfateev\AppData\Local\Programs\Python\Python36\lib\csv.py", line 111, in __next__
    self.fieldnames
  File "C:\Users\ivfateev\AppData\Local\Programs\Python\Python36\lib\csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "C:\Users\ivfateev\AppData\Local\Programs\Python\Python36\lib\site-packages\unicodecsv\py3.py", line 55, in __next__
    return self.reader.__next__()
  File "C:\Users\ivfateev\AppData\Local\Programs\Python\Python36\lib\site-packages\unicodecsv\py3.py", line 51, in <genexpr>
    f = (bs.decode(encoding, errors=errors) for bs in f)
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by ryanhiebert** [comment]
Can you give a minimal example of how to reproduce this? Off the top of my head, I'm thinking that you may not be opening the file in bytes mode. You need to open it in bytes mode, because unicodecsv reads and writes bytes from files, not text.

If you prefer to not open a file in bytes mode, you might check out [backports.csv](https://github.com/ryanhiebert/backports.csv), which uses a text interface instead, the same as the Python 3 csv module does.

**Comment by Vicedivic** [comment]
How do you open a file in bytes mode?

**Comment by ryanhiebert** [comment]
`open('filename.csv', 'wb')`. The `b` in the mode setting is the bit that works the magic.

**Comment by Vicedivic** [comment]
OK, thanks!
