### ISSUE TITLE
problem in encode string 

### ISSUE THREAD

**Issue by MotiBaadror** [jdunck/python-unicodecsv#83]
```pycon
>>> yelp_soup=BeautifulSoup(yelp_r.text,'html.parser')
>>> print(yelp_soup.prettify())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 33349: character maps to <undefined>
>>>
```

**Comment by ryanhiebert** [comment]
I don't understand what this has to do with `python-unicodecsv`. The error looks like it's coming up from calling a BeautifulSoup function.

Closing because of that, but I'll be listening if you tell me I'm wrong.
