### ISSUE TITLE
Receiving UnicodeDecodeError on CSV file

### ISSUE THREAD

**Issue by PJAMESR** [jdunck/python-unicodecsv#86]
Hello, so I am trying to go througha  huge data file using a machine learning software that requires the text to be in Unicode. I have been working on this problem for a number of hours and it is quite urgent. Here is my code:
```
TEST_SENTENCES = []
with open('Book2.csv', 'rb') as csvfile:
    reader = unicodecsv.DictReader(csvfile)
    for row in reader:
        TEST_SENTENCES.append(row["Tweet"])
    for x in [TEST_SENTENCES]:
        codecs.encode(x, 'utf-8')
```

Here is the error I am receiving:
`Traceback (most recent call last):
  File "C:\Users\pjame\Desktop\DeepMoji-master\examples\score_texts_emojis.py", line 25, in <module>
    for row in reader:
  File "C:\Python27\lib\site-packages\unicodecsv\py2.py", line 217, in next
    row = csv.DictReader.next(self)
  File "C:\Python27\lib\csv.py", line 108, in next
    row = self.reader.next()
  File "C:\Python27\lib\site-packages\unicodecsv\py2.py", line 128, in next
    for value in row]
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 254: unexpected end of data`
Does anyone have any idea how I can get around this error? I see that for some reason csv is being called in one of the error messages, but I am not sure why. It could be in the parts of the file I did not write which can be found here: [](https://github.com/bfelbo/DeepMoji/blob/master/examples/score_texts_emojis.py)

If anyone has any ideas, or fixes to this, I would be so so appreciative. Even just being able to find and delete the lines in the CSV file that are errors would be super useful.

**Comment by PJAMESR** [comment]
So, a very odd update. 
I narrowed an error message down to 100 tweets, then kept narrowing it. I ended up having about 15 tweets in the end. I copy pasted 7 from one csv to the file that I was reading, and the program worked. Then I copied the other 8, and to my surprise, when I had once gotten an error before with the exact same data, so the decoding now worked on the same data it had not worked on just 10 seconds before.

**Comment by PJAMESR** [comment]
So I am not sure what is going on, but it is definitely something very weird. The same data is sometimes working when copy pasted from the "data" csv to the "read" csv, and it just seems to be randomly breaking. For example. where I was having trouble with something in the 300s before, now I have been able to upload even up to 600 with no problem at all.
