### ISSUE TITLE
Failed to install on windows

### ISSUE THREAD

**Issue by alexsilva** [jdunck/python-unicodecsv#88]
Python 3.7.2 `Windows x86 embeddable zip file`
Windows 10
pip 19.0.1

I have already discovered that the failure is because the unicodecsv package directory is not in sys.path but I do not know how to resolve the installation.

unicodecsv was declared inside a `requirements.txt` script

Installation command:

`python.exe -m pip install -r requirements.txt --no-cache-dir`

```
Collecting unicodecsv (from -r requirements.txt (line 74))
  Using cached https://files.pythonhosted.org/packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\genio\AppData\Local\Temp\pip-install-ckob5edl\unicodecsv\setup.py", line 5, in <module>
        version = __import__('unicodecsv').__version__
    ModuleNotFoundError: No module named 'unicodecsv'
```

Any idea how to solve it ?

**Comment by DiamondHunters** [comment]
clone this repo and edit `setup.py`
insert
`import sys
sys.path.append('')`
before
`version = __import__('unicodecsv').__version__`
then 
`python setup.py install`
It works fine for me
